# Generated by Django 5.0.4 on 2024-04-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
